### ISSUE TITLE
Size and pageviews

### ISSUE THREAD

**Issue by nemobis** [anjalief/wikipedia_bias_public#1]
Thanks for your work using Wikidata.

>  Shorter articles can indicate that articles were written less carefully, 

Beyond a certain size it's usually the opposite. Articles grow uncontrollably and it takes a lot of effort to remove fluff. This also has led to initiatives like https://en.wikipedia.org/wiki/Wikipedia:De-bloat-athon . Therefore it's often useful to consider the absolute size of the diffs contributed to a page: both removals and additions of text are valuable.

> e.g., editors may have spent less time uncovering details to include in the article. They can also indicate that information is less carefully presented—in examining matched pairs, we often found that information in Asian American peoples’ articles was displayed in lists or tables, whereas information in comparison articles was presented in descriptive paragraphs.  [...] Notably, all articles about gender and racial minorities were written more recently 

Good point but at least for popular articles the growth is directly proportional to pageviews. The number of edits can be a proxy for pageviews, as they're both related to popularity, but patterns can diverge.

**Comment by anjalief** [comment]
Thanks so much for this feedback. We will incorporate it in revisions of the paper
